### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by Elwood4415** [waymondo/vscode-todoist#32]
I installed vscode-todoist v4. Unfortunately, I put in the wrong thing instead of the token. Now, whenever I click on Todoist in the command pallet, I get a code 401 error message. I can find no way to clear that out. I have uninstalled, rebooted, and reinstalled the extension, and I still get the same error message. I finally installed version 3, and was able to put the correct token in, and version 3 works fine. But when I go back to version 4, I get the same error code even though the API token is now correct in the json settings. Is there any way to clear out the error message so that I can use version 4?

**Comment by dubisdev** [comment]
Hi @Elwood4415 and sorry for the late response (we are currently busy and this extension is practically unmaintained)

The problem here is that version 4 uses a special storage to store the secrets (they are not being saved in a plain json as other settings). I have created an special command called "Todoist Modify token" to make users able to modify their API token.

![image](https://github.com/waymondo/vscode-todoist/assets/77246331/6332ce57-5706-4a57-ae67-45eb3e9bd5d9)

This version is pending to be released as the extensions store token in the CI has expired (you can have more info here #33)

Once we fix the CI I'll release a new version and this command will be available for all.

**Comment by dubisdev** [comment]
Hi @Elwood4415 the new version (0.5.0) has been published. The new command should be now available.
