### ISSUE TITLE
CI: API token has expired

### ISSUE THREAD

**Issue by dubisdev** [waymondo/vscode-todoist#33]
Hi @waymondo :)

I hope all is going well. I opened this issue as I have been working in a new version that addresses #32 

The CI seems to be failing because of your token of the extensions store (it has expired)

![image](https://github.com/waymondo/vscode-todoist/assets/77246331/0a86a00a-325b-4628-8ecf-0448a033496f)

Here you have some info about how to generate a new one: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Let me know if you are interested in continuing hosting the extension in your account. I can take care of it if it's neccessary.

Thank you 🤝

**Comment by waymondo** [comment]
@dubisdev thanks for the ping. i'd be happy to turn maintenance of this over to you, if you'd accept. i don't work on/with VSCode these days. just let me know what i'd need to do in that case.

**Comment by dubisdev** [comment]
It's ok for me.

Could you transfer me this repo so I can manage the secrets for the CI? I'm not sure if there is another option like giving me more permissions over the repo. That would be also perfect.

If you agree, nexts steps are:
1. Changing the current `publisher` field in the package.json so I can publish updates from my account
2. [Reach to the VS code extensions team ](https://github.com/microsoft/vscode-discussions/discussions/1) so they can deprecate the older version in favor of the new version (so you don't have to do it manually)
3. I can give you credit through a mention in the [`package.json` author field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#people-fields-author-contributors), in the README or in any other way that you consider appropriate

**Comment by waymondo** [comment]
i took at look the link in your original post again and it seemed simple enough to just generate a new access token - simpler than transferring everything other to you at least. i went ahead and did that and re-ran the latest failed CI build and it seemed to pass. 

i guess i'll just retain ownership of the repo & extension for now. let me know if you need anything else from me regarding this. otherwise feel free to continue to manage any updates to this repo as you see fit. thanks a bunch!

**Comment by dubisdev** [comment]
Perfect! Thank you @waymondo , I'll close this issue then :)
